common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: im1coolguy

development:
  <<: *common
  database: mancala

test:
  <<: *common
  database: mancalaTest
